# Generated by Django 5.0.1 on 2024-01-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='image',
            field=models.ImageField(default='', upload_to='main_app/static/uploads'),
        ),
    ]
